name: Build and Publish Docker Image

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: lewbuntu

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build Docker image
        run: docker build -t $IMAGE_NAME .

      - name: Tag Docker image
        run: docker tag $IMAGE_NAME ghcr.io/${{ github.repository }}/$IMAGE_NAME:${{ github.sha }}

      - name: Push Docker image
        run: docker push ghcr.io/${{ github.repository }}/$IMAGE_NAME:${{ github.sha }}